version: '3.9'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5433:${DB_PORT}

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PORT=6379

  app:
    build: ./
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    env_file:
      - .setenv.sh