version: '3.9'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5433:${DB_PORT}

  app:
    build: ./
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - .setenv.sh